[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = ";"
key = 43
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[118;1u"
key = 47
mods = "Control"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true

[window.padding]
x = 3
y = 3
